# Generated by Django 5.2.6 on 2025-09-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_terms_accepted'),
    ]

    operations = [
    ]
